# Generated by Django 4.1.7 on 2023-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0002_remove_profile_name_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=None),
        ),
    ]
