# Generated by Django 4.1.7 on 2023-03-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='definition',
            new_name='description',
        ),
    ]
