# Generated by Django 4.1.7 on 2023-03-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0004_rename_definition_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture'),
        ),
    ]
